version: 2
jobs:
  build:
    working_directory: ~/pyam-analysis
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: ls
          command: pwd && ls
      - run:
          name: CIRCLE_ARTIFACTS
          command: |
            mkdir /ci-artifacts;
            ls /ci-artifacts;
      - run:
          name: Build Py2 Docker Image
          command: /bin/sh -c "ln -f -s ci/py2/Dockerfile Dockerfile && docker build -t pyam-analysis/pyam-analysis-py2:latest ."
      - run:
          name: Python2 Tests
          command:  docker run -v /ci-artifacts:/test-artifacts pyam-analysis/pyam-analysis-py2:latest python2 -m pytest -v --mpl --mpl-results-path=/test-artifacts /pyam-analysis/tests
          when: always
      - run:
          name: Build Py3 Docker Image
          command: /bin/sh -c "ln -f -s ci/py3/Dockerfile Dockerfile && docker build -t pyam-analysis/pyam-analysis-py3:latest ."
      - run:
          name: Python3 Tests
          command:  docker run -v /ci-artifacts:/test-artifacts pyam-analysis/pyam-analysis-py3:latest python3 -m pytest -v --mpl --mpl-results-path=/test-artifacts /pyam-analysis/tests
          when: always
      - run:
          name: check artifacts
          command: ls /ci-artifacts
          when: on_fail
      - store_artifacts:
          path: /ci-artifacts